name: Scraper Diario

on:
  schedule:
    - cron: '0 13 * * *' # Ejecutar diario a las 8 AM NY
  workflow_dispatch: # Permite bot√≥n manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python scraping_iglesias.py
      - uses: actions/upload-artifact@v4
        with:
          name: leads-csv
          path: "*.csv"
          retention-days: 5
